Changes for PowerAPI monitoring

diff --git a/.github/workflows/update_pr_compliance.yml b/.github/workflows/update_pr_compliance.yml
--- a/.github/workflows/update_pr_compliance.yml
+++ b/.github/workflows/update_pr_compliance.yml
@@ -1,18 +1,16 @@
-name: Update Pr Compliance
-
-on:
-  pull_request:
-    types: [opened, edited, reopened, synchronize]
-    branches:
-      - master
-    paths:
-      - scripts/pr_compliance.py
-  
 jobs:
   run-tests:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-python@v3
-      - name: run script
-        run: python3 scripts/pr_compliance.py run-tests > test.log || { echo "::error::pr_compliance.py $(cat test.log)" && exit 1; }
+    - continue-on-error: true
+      uses: actions/checkout@v3
+    - continue-on-error: true
+      uses: actions/setup-python@v3
+    - continue-on-error: true
+      name: run script
+      run: python3 scripts/pr_compliance.py run-tests > test.log || { echo "::error::pr_compliance.py
+        $(cat test.log)" && exit 1; }
+name: Update Pr Compliance
+on:
+  repository_dispatch:
+    types: trigger-ga___update_pr_compliance.yml
